spring:
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/harcamatakip
    username: root
    password: 321514
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
  logging:
    level:
      org.springframework.security.web: DEBUG
server:
  port: 8080
